FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app
COPY data ./data
COPY start.py ./start.py

EXPOSE 8000

CMD ["python", "start.py"]
